CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_double_weighted-sampler_0/config_eval_snap.yaml
CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_double_weighted-sampler_1/config_eval_snap.yaml
CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_double_weighted-sampler_2/config_eval_snap.yaml
CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_double_weighted-sampler_3/config_eval_snap.yaml
CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_double_weighted-sampler_4/config_eval_snap.yaml

CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_single_weighted-sampler_0/config_eval_snap.yaml
CUDA_VISIBLE_DEVICES=1 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_single_weighted-sampler_1/config_eval_snap.yaml
CUDA_VISIBLE_DEVICES=1 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_single_weighted-sampler_2/config_eval_snap.yaml
CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_single_weighted-sampler_3/config_eval_snap.yaml
CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_single_weighted-sampler_4/config_eval_snap.yaml

# prospective
CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_double_weighted-sampler_prospective.yaml
CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_single_weighted-sampler_prospective.yaml

# chaozhou
CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_double_weighted-sampler_chaozhou.yaml
CUDA_VISIBLE_DEVICES=0 python uncertainty_classification.py -c configs/ted_classification/dinov3_huge_448x896_lora_r8a16_d01_dp01_f1_aug_v3_single_weighted-sampler_chaozhou.yaml